include_guard(GLOBAL)

# The SDK is a build dependency. Its location and digest come from the authenticated
# GitHub Release response rather than user-maintained CMake cache variables.
set(RTX_VIDEO_SDK_CACHE "${CMAKE_BINARY_DIR}/_driver_deps/rtx-video-sdk")
if (NOT "$ENV{RTX_VIDEO_SDK_URL}" STREQUAL "")
    set(RTX_VIDEO_SDK_URL "$ENV{RTX_VIDEO_SDK_URL}" CACHE STRING
        "GitHub Release URL of the authorized RTX Video SDK" FORCE)
else ()
    set(RTX_VIDEO_SDK_URL "" CACHE STRING "GitHub Release URL of the authorized RTX Video SDK")
endif ()

function(_rtx_sdk_valid root output)
    set(_valid TRUE)
    foreach (_file include/nvsdk_ngx.h include/nvsdk_ngx_helpers_truehdr.h
            lib/Windows/x64/nvsdk_ngx_d.lib bin/Windows/x64/rel/nvngx_truehdr.dll)
        if (NOT EXISTS "${root}/${_file}" OR IS_DIRECTORY "${root}/${_file}")
            set(_valid FALSE)
        endif ()
    endforeach ()
    set(${output} ${_valid} PARENT_SCOPE)
endfunction()

function(_rtx_sdk_download url output accept timeout expected_hash result)
    set(${result} FALSE PARENT_SCOPE)
    foreach (_attempt RANGE 1 3)
        file(DOWNLOAD "${url}" "${output}.part"
            STATUS _status TLS_VERIFY ON TIMEOUT ${timeout} INACTIVITY_TIMEOUT 30
            HTTPHEADER "Authorization: Bearer ${_SUNSHINE_RTX_VIDEO_SDK_TOKEN}"
            HTTPHEADER "Accept: ${accept}"
            HTTPHEADER "User-Agent: Foundation-Sunshine-build"
            HTTPHEADER "X-GitHub-Api-Version: 2022-11-28")
        list(GET _status 0 _code)
        if (_code EQUAL 0 AND EXISTS "${output}.part")
            file(SIZE "${output}.part" _size)
            set(_verified FALSE)
            if (_size GREATER 0)
                if (expected_hash)
                    file(SHA256 "${output}.part" _hash)
                    if (_hash STREQUAL expected_hash)
                        set(_verified TRUE)
                    endif ()
                elseif (_size LESS_EQUAL 4194304)
                    set(_verified TRUE)
                endif ()
            endif ()
            if (_verified)
                file(REMOVE "${output}")
                execute_process(COMMAND "${CMAKE_COMMAND}" -E rename "${output}.part" "${output}"
                    RESULT_VARIABLE _rename_error OUTPUT_QUIET ERROR_QUIET)
                if (_rename_error STREQUAL "0")
                    set(${result} TRUE PARENT_SCOPE)
                    return()
                endif ()
            endif ()
        endif ()
        file(REMOVE "${output}.part")
        # Request headers and libcurl diagnostics may contain credentials.
        message(STATUS "RTX Video SDK transfer ${_attempt}/3 failed or did not pass validation")
    endforeach ()
endfunction()

function(_rtx_sdk_extracted source output)
    set(${output} "" PARENT_SCOPE)
    file(GLOB_RECURSE _headers "${source}/nvsdk_ngx_helpers_truehdr.h")
    list(LENGTH _headers _count)
    if (_count EQUAL 1)
        list(GET _headers 0 _header)
        get_filename_component(_include "${_header}" DIRECTORY)
        get_filename_component(_root "${_include}" DIRECTORY)
        _rtx_sdk_valid("${_root}" _valid)
        if (_valid)
            set(${output} "${_root}" PARENT_SCOPE)
        endif ()
    endif ()
endfunction()

function(_rtx_sdk_asset_from_metadata metadata expected_url asset_id digest reason)
    set(${asset_id} "" PARENT_SCOPE)
    set(${digest} "" PARENT_SCOPE)
    string(JSON _count ERROR_VARIABLE _json_error LENGTH "${metadata}" assets)
    if (_json_error OR _count LESS 1)
        set(${reason} "SDK release metadata is invalid or empty" PARENT_SCOPE)
        return()
    endif ()
    math(EXPR _last "${_count} - 1")
    foreach (_index RANGE 0 ${_last})
        string(JSON _asset_url ERROR_VARIABLE _url_error GET "${metadata}" assets ${_index} browser_download_url)
        if (NOT _url_error AND _asset_url STREQUAL expected_url)
            string(JSON _id ERROR_VARIABLE _id_error GET "${metadata}" assets ${_index} id)
            string(JSON _state ERROR_VARIABLE _state_error GET "${metadata}" assets ${_index} state)
            string(JSON _digest ERROR_VARIABLE _digest_error GET "${metadata}" assets ${_index} digest)
            string(LENGTH "${_digest}" _digest_length)
            if (_id_error OR _state_error OR _digest_error OR
                NOT _id MATCHES "^[0-9]+$" OR NOT _state STREQUAL "uploaded" OR
                NOT _digest_length EQUAL 71 OR NOT _digest MATCHES "^sha256:[a-fA-F0-9]+$")
                set(${reason} "the SDK asset has no usable GitHub SHA-256 digest" PARENT_SCOPE)
                return()
            endif ()
            string(SUBSTRING "${_digest}" 7 64 _sha256)
            string(TOLOWER "${_sha256}" _sha256)
            set(${asset_id} "${_id}" PARENT_SCOPE)
            set(${digest} "${_sha256}" PARENT_SCOPE)
            return()
        endif ()
    endforeach ()
    set(${reason} "the configured SDK asset was not found" PARENT_SCOPE)
endfunction()

function(sunshine_find_rtx_video_sdk output reason)
    set(${output} "" PARENT_SCOPE)
    set(${reason} "private SDK download configuration is unavailable" PARENT_SCOPE)
    set(_url "${RTX_VIDEO_SDK_URL}")
    if (NOT _url)
        return()
    endif ()
    if (NOT _url MATCHES "^https://github\\.com/([A-Za-z0-9_.-]+)/([A-Za-z0-9_.-]+)/releases/download/([^/?#]+)/([^/?#]+)$")
        set(${reason} "SDK URL must identify one GitHub Release asset" PARENT_SCOPE)
        return()
    endif ()
    set(_repository "${CMAKE_MATCH_1}/${CMAKE_MATCH_2}")
    set(_tag "${CMAKE_MATCH_3}")
    string(SHA256 _url_key "${_url}")
    get_filename_component(_cache "${RTX_VIDEO_SDK_CACHE}" ABSOLUTE)
    set(_lookup "${_cache}/lookups/${_url_key}")
    file(MAKE_DIRECTORY "${_lookup}")
    file(LOCK "${_lookup}/download.lock" GUARD FUNCTION TIMEOUT 60 RESULT_VARIABLE _lock_error)
    if (NOT _lock_error STREQUAL "0")
        set(${reason} "SDK cache is busy" PARENT_SCOPE)
        return()
    endif ()

    # A local lookup makes Ninja-triggered CMake regeneration independent of the
    # credential after the first authenticated configure. Supplying a credential
    # refreshes metadata, so replacing an asset at the same URL is observed.
    set(_metadata "${_lookup}/release.json")
    if (_SUNSHINE_RTX_VIDEO_SDK_TOKEN)
        _rtx_sdk_download("https://api.github.com/repos/${_repository}/releases/tags/${_tag}"
            "${_metadata}" "application/vnd.github+json" 60 "" _metadata_ready)
        if (NOT _metadata_ready)
            if (EXISTS "${_metadata}")
                message(STATUS "RTX Video SDK metadata refresh failed; using the last successful authenticated lookup")
                set(_metadata_ready TRUE)
            else ()
                set(${reason} "SDK release lookup failed" PARENT_SCOPE)
                return()
            endif ()
        endif ()
    elseif (EXISTS "${_metadata}")
        set(_metadata_ready TRUE)
    else ()
        set(${reason} "no authenticated metadata or verified SDK cache is available" PARENT_SCOPE)
        return()
    endif ()

    file(SIZE "${_metadata}" _metadata_size)
    if (_metadata_size LESS 2 OR _metadata_size GREATER 4194304)
        set(${reason} "SDK release metadata has an invalid size" PARENT_SCOPE)
        return()
    endif ()
    file(READ "${_metadata}" _metadata_json)
    _rtx_sdk_asset_from_metadata("${_metadata_json}" "${_url}" _asset_id _sha256 _asset_reason)
    if (NOT _asset_id OR NOT _sha256)
        set(${reason} "${_asset_reason}" PARENT_SCOPE)
        return()
    endif ()

    set(_entry "${_cache}/artifacts/${_sha256}")
    set(_archive "${_entry}/sdk.zip")
    file(MAKE_DIRECTORY "${_entry}")
    set(_archive_valid FALSE)
    if (EXISTS "${_archive}")
        file(SHA256 "${_archive}" _actual)
        if (_actual STREQUAL _sha256)
            set(_archive_valid TRUE)
        endif ()
    endif ()
    if (NOT _archive_valid)
        if (NOT _SUNSHINE_RTX_VIDEO_SDK_TOKEN)
            set(${reason} "the verified SDK archive is unavailable" PARENT_SCOPE)
            return()
        endif ()
        # The API URL is derived from the validated repository and numeric asset ID.
        _rtx_sdk_download("https://api.github.com/repos/${_repository}/releases/assets/${_asset_id}"
            "${_archive}" "application/octet-stream" 300 "${_sha256}" _archive_ready)
        if (NOT _archive_ready)
            set(${reason} "SDK download or GitHub digest verification failed" PARENT_SCOPE)
            return()
        endif ()
    endif ()

    set(_source "${_entry}/source")
    if (EXISTS "${_entry}/complete")
        _rtx_sdk_extracted("${_source}" _root)
        if (_root)
            set(${output} "${_root}" PARENT_SCOPE)
            return()
        endif ()
    endif ()

    get_filename_component(_cache_real "${_cache}" ABSOLUTE)
    get_filename_component(_source_real "${_source}" ABSOLUTE)
    cmake_path(IS_PREFIX _cache_real "${_source_real}" NORMALIZE _within_cache)
    if (NOT _within_cache)
        set(${reason} "invalid SDK extraction directory" PARENT_SCOPE)
        return()
    endif ()
    file(REMOVE "${_entry}/complete")
    file(REMOVE_RECURSE "${_source}")
    file(MAKE_DIRECTORY "${_source}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E tar xf "${_archive}"
        WORKING_DIRECTORY "${_source}" RESULT_VARIABLE _extract_result
        OUTPUT_QUIET ERROR_QUIET TIMEOUT 120)
    _rtx_sdk_extracted("${_source}" _root)
    if (NOT _extract_result STREQUAL "0" OR NOT _root)
        set(${reason} "SDK extraction failed or required SDK files are missing" PARENT_SCOPE)
        return()
    endif ()
    file(WRITE "${_entry}/complete" "${_sha256}\n")
    set(${output} "${_root}" PARENT_SCOPE)
endfunction()
